name: "Changelog"
on:
  push:
    branches:
      - main
jobs:
  update-changelog:
    name: Update Changelog and version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Update Changelog and version
        id: changelog
        run: |
          chmod +x ./changelog.sh
          ./changelog.sh
        shell: bash
      - name: Post Changelog to Slack
        shell: bash
        if: ${{ always() && (steps.changelog.outputs.status == 'updated') }}
        run: |
          echo "STATUS ${{ steps.changelog.outputs.status }}"
          echo "TEXT ${{ steps.changelog.outputs.text }}"
