name: "Changelog"
on:
  push:
    branches:
      - main
jobs:
  update-changelog:
    name: "Update Changelog and version"
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: echo "LS $(ls .)"
      - name: Generate Auto Changelog
        run: ./changelog.sh
        shell: bash
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
