name: "Changelog"
on:
  push:
    branches:
      - main
jobs:
  update-changelog:
    name: "Update Changelog and version"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Current branch
        run: echo $(git --no-pager branch --show-current)
        shell: bash
      - name: Log
        run: echo $(git --no-pager log -100 HEAD --format="%s")
        shell: bash
      - name: Generate Auto Changelog
        run: |
          chmod +x ./changelog.sh
          ./changelog.sh
        shell: bash
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
